### ISSUE TITLE
Add new parser is imposible!

### ISSUE THREAD

**Issue by ai2ci** [raspi/pypdnsrest#2]
Hi, is the best way to skip used parser? I thing it skips just added parser. 
Sorry, it's very blocking bug.

https://github.com/raspi/pypdnsrest/blob/2d8d7d68b6c819f8d38f66017b4317a7b45e48e4/pypdnsrest/client.py#L209

**Comment by raspi** [comment]
Looks like brain fart. I'll fix it.

**Comment by raspi** [comment]
Fixed in ed087a93457dbde54071cc5a6c593696a7e475ca
