### ISSUE TITLE
TTL looks useless and blocking

### ISSUE THREAD

**Issue by ai2ci** [raspi/pypdnsrest#4]
Hi there, it's me again.
I mean this part of code especially ttl looks useless.
So creating of MX record is imposible. 
https://github.com/raspi/pypdnsrest/blob/d45f89721108d0718c791de91c2cdf31ab7cee9b/pypdnsrest/dnsrecords.py#L292-L300

**Comment by raspi** [comment]
Could you provide example code?

It's meant to be used like this: https://github.com/raspi/pypdnsrest/blob/05714c8011fed6469f6cca207ab538ace13c7549/tests/records/test_mx.py

```
myzone = "foo.bar."
record = DNSMxRecord(myzone)
rec.set_data(DNSMxRecordData("mail.{0}".format(myzone), 10))
```

**Comment by raspi** [comment]
I'm closing this on lack of feedback. Please re-open if you have more information.

**Comment by rbikbov** [comment]
@raspi 
When I try to do this:
record = parser.parse(i['name'], recs['content'], int(i['ttl']))  # recs['content'] = '10 test.mx.record.com.'
pdns_api_client.add_record(self.cname, record)  # record = '1234. 600 MX 10 test.mx.record.com. 3600'

I get this response from PDNS:
'{
    "error": "Record 1234./MX \\'10 test.mx.record.com. 3600\\': All data was not consumed"
}'
